# version: '3.8'

# services:
#   postgres:
#     image: postgres
#     ports:
#       - "5433:5432"  # Cổng trên máy host : cổng trong container
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: exercise_db

#   run:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: run-1
#     depends_on:
#       - postgres
#     volumes:
#       - .:/app

version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: my_postgres
    environment:
      POSTGRES_DB: exercise_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: exercise_db
      DB_USER: postgres
      DB_PASSWORD: postgres

volumes:
  postgres_data:
