# docker-compose.yml

version: '3.8'

services:
  run:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exercise6_runner
    volumes:
      - .:/app
    working_dir: /app
    command: python3 main.py
